name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Docker install
      uses: docker/setup-buildx-action@v3

    - name: Docker hub login
      uses: docker/login-action@v3
      with:
         username: ${{ secrets.DOCKERHUB_LOGIN }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Docker image Build and Push 
      run: |
        commit_id=$(git rev-parse --short HEAD)
        image="${{ secrets.DOCKERHUB_LOGIN }}/simple-calc:$commit_id"
        docker build --file Dockerfile --tag "$image" .
        docker images
        docker push "$image"

        image_latest="${{ secrets.DOCKERHUB_LOGIN }}/simple-calc:latest"
        docker tag "$image" "$image_latest"
        docker images
        docker push "$image_latest"
