name: Run Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install libcunit
      run: sudo apt-get install -y gcc libcunit1-dev

    - name: Build unit tests
      run: gcc test.c -o test-calc -l cunit
    
    - name: Run unit tests
      run: ./test-calc
      
  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Docker
      uses: docker/setup-buildx-action@v3

    - name: Build image and Run test
      run: |
         pull_req_num=${{ github.event.pull_request.number }}
         calc_image="yurtsweta/calc:pr-${pull_req_num}"
         docker build --tag "$calc_image" .
         chmod +x e2e-tests.sh
         ./e2e-tests.sh "$calc_image"
    
 
